const Type = {
    SET_FLIGHTS: "SET_FLIGHTS",

    SORT_ASCENDING: "SORT_ASCENDING",
    SORT_DESCENDING: "SORT_DESCENDING",
    SORT_TRIP_TIME: "SORT_TRIP_TIME",

    FILTER_ONE_CHANGE: "FILTER_ONE_CHANGE",
    FILTER_NONE_CHANGES: "FILTER_NONE_CHANGES",

    SET_PRICE_FROM: "SET_PRICE_FROM",
    SET_PRICE_TO: "SET_PRICE_TO",

    SET_AIRLINES: "SET_AIRLINES",

    SET_LIMIT: "SET_LIMIT"
}


export default Type;