const Type = {
    SET_FLIGHTS: "SET_FLIGHTS",

    SORT_ASCENDING: "SORT_ASCENDING",
    SORT_DESCENDING: "SORT_DESCENDING",
    SORT_TRIP_TIME: "SORT_TRIP_TIME",

    FILTER_BY_TRANSFERS: "FILTER_BY_TRANSFERS",
    FILTER_BY_PRICE: "FILTER_BY_PRICE",

    SET_PRICE_FROM: "SET_PRICE_FROM",
    SET_PRICE_TO: "SET_PRICE_TO",


    SET_AIRLINES: "SET_AIRLINES",

    SET_LIMIT: "SET_LIMIT",

    SET_ALL_TRANSFERS: "SET_ALL_TRANSFERS",
}


export default Type;